services:
  app:
    build:
      context: ./app
      args:
        - PORT=3000
        - VITE_API_URL=http://54.207.125.158:8080
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - api
  api:
    build:
      context: ./api
      args:
        - PORT=:8080
        - GIN_MODE=release
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
