services:
  app:
    build:
      context: ./app
      args:
        - PORT=3000
        - VITE_API_URL=http://api:8080
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - api
  api:
    build:
      context: ./api
      args:
        - PORT=:8080
        - GIN_MODE=release
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME